# Generated by Django 6.0.5 on 2026-06-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorit_book_app', '0003_game_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_created', to='favorit_book_app.user'),
        ),
    ]
