# Generated by Django 6.0.5 on 2026-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorit_book_app', '0005_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload_avatar',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
